image: hashicorp/terraform:latest

variables:
  TF_STATE_BUCKET: "your-terraform-state-bucket"

before_script:
  - apk --no-cache add bash git
  - chmod +x ${CI_PROJECT_DIR}/ci/manage-users.sh

stages:
  - detect
  - validate
  - plan
  - apply

detect-changes:
  stage: detect
  script:
    - ${CI_PROJECT_DIR}/ci/manage-users.sh detect > changes.txt
    - if [ -s changes.txt ]; then echo "CHANGES_PRESENT=true" > changes.env; fi
  artifacts:
    paths:
      - changes.txt
    reports:
      dotenv: changes.env
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

include:
  - local: 'ci/terraform-pipeline.yml'
    rules:
      - if: '$CHANGES_PRESENT'